### ISSUE TITLE
Align Application Descriptor Schema with latest structural updates

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-git-migration-modeler#29]
The CBS in the ibm/dbb community repository have evolved via [PR299](https://github.com/IBM/dbb/pull/299) to reference external dependencies differently.

Migration Modeler needs to accommodate the new schema.

For dependencies:

```
dependencies: 
- name: ”retirementCalculator"
  type: "release"
  reference: "rel-1.2.0"
  buildid: "build-20241112.1"
```

And similarly for the baseline reference:

```
baselines:
- branch: "main"
  type: "release"
  reference: "rel-1.4.0"
  buildid: "20250224.4" 

```
